### ISSUE TITLE
Won't recongize inputs except from attached Joy-Cons

### ISSUE THREAD

**Issue by octopuserectus** [WerWolv/libtesla#1]
Neither input from detached Joy-Cons (as player 1 or player 2), nor Pro Controller (safe guess that any other connected controllers) isn't recognized to open overlay.
Expected behavior: accept input from any player number on any controller.

**Comment by WerWolv** [comment]
That's a bug yeah. Easy to fix though luckily. Will take care of that as soon as I can

**Comment by WerWolv** [comment]
Fixed in the latest release
