### ISSUE TITLE
Should allow userAppInit and userAppExit

### ISSUE THREAD

**Issue by nedex** [WerWolv/libtesla#31]
Hello there.
Since i'm using extra services, like `socket` and `nifm`, it would be great if an user could define custom additional services initialization to their overlays, as it happens here (`userAppInit` and `userAppExit`):
https://github.com/switchbrew/libnx/blob/master/nx/source/runtime/init.c#L102

At the time of writing i have to modify the `tesla.hpp` file.
Thanks!

**Comment by nedex** [comment]
Nevermind, I just found out about `initServices` and `exitServices`.
Another question, why is it needed to call `smExit` in `doWithSmSession` ?

I have to call `smInitialize` anyways, otherwise the `getaddrinfo` function will fail..

**Comment by WerWolv** [comment]
initServices already has it initialized. But yeah, you should use the tsl::hlp::doWithSMSession function whenever you need to initialize a service anywhere outside of initServices. This is done so other services don't run out on sm sessions themselves when launched after tesla
