### ISSUE TITLE
menu don't show at all

### ISSUE THREAD

**Issue by GitEz-code** [WerWolv/libtesla#44]
i have reinstalled: atmosphere, hekate, nx-ovlloader, tesla menu and it doesn't work.

is someone can help me ?

**Comment by lookye** [comment]
If you are playing in docked mode do this:

> Go under Settings -> TV Output and make sure that the display scaling is set to 100%. Anything else will cause the menu to not appear anymore in games.

**Comment by GitEz-code** [comment]
it doesn't work docked and undocked, and i have set the display scaling at 100%

**Comment by masagrator** [comment]
Well, this is wrong repo. Make an issue in nx-ovlloader repo
