### ISSUE TITLE
Occasional crash if TV Resolution is not set as 720p in Docked mode

### ISSUE THREAD

**Issue by ghost** [WerWolv/libtesla#50]
How to reproduce: 
1. Put console in the Dock.
2. Set "TV Resolution" to 480p or 1080p (or Automatic if your TV is 1080p/4K compatible)
3. Load Tesla-Menu, open and close any overlay for multiple times (easier to reproduce)
4. AMS will crash with 2168-0002 (Data Abort):
```
Process Info:
    Process Name:                ovlloader
    Program ID:                  420000000007e51a
Stack Trace:
        ReturnAddress[00]:       00000008b03cfc48 (Tesla-Menu + 0x1ac48)
        ReturnAddress[01]:       00000008b03d05f4 (Tesla-Menu + 0x1b5f4)
        ReturnAddress[02]:       00000008b03c2ce8 (Tesla-Menu + 0xdce8)
        ReturnAddress[03]:       00000008b03b53f0 (Tesla-Menu + 0x3f0)
        ReturnAddress[04]:       0000000000000000
```

Other overlays can crash in the same way (with their names in `Stack Trace`).
And all of them point to [framebufferClose(&this->m_framebuffer)](https://github.com/WerWolv/libtesla/blob/640629f49f9e8997ef0769b21b26f4fc177c736f/include/tesla.hpp#L1052) in `tsl::gfx::Renderer::exit()`. 
So I suppose the issue is related to libtesla.

Full crash report: [01626455123_420000000007e51a.log.zip](https://github.com/WerWolv/libtesla/files/6832362/01626455123_420000000007e51a.log.zip)

I'm using Mariko Iowa(Red-Box) Model with official Dock, latest AMS(0.19.5 M), nx-ovlloader(1.0.6) and Tesla-Menu(1.1.2). 
Tested in HOS 12.1.0/10.2.0, without any other sysmodules running.

**Comment by Cooler3D** [comment]
The problem is still there. If it doesn't get fixed soon, I plan to do it myself.

**Comment by WerWolv** [comment]
Please do. I'm happy to merge it if you manage to find the issue.

**Comment by masagrator** [comment]
Provided PR here:
https://github.com/WerWolv/libtesla/pull/65

Compiled Tesla Menu with this PR:
[ovlmenu.zip](https://github.com/WerWolv/libtesla/files/11126965/ovlmenu.zip)

Since issue is inside libtesla, all overlays would require to be recompiled to remove random crashes completely.

Happy April Fools Day!
