### ISSUE TITLE
run make command from the libtesla-1.3.3/example/, too many not declared errors

### ISSUE THREAD

**Issue by sir1st** [WerWolv/libtesla#52]
just run the make command without do anything with the source code (libtesla) (i just download the lasted source code from github).
platform: win10, devkitpro with switch-dev, switch-freetype, switch-zlib.
![微信截图_20211114193610](https://user-images.githubusercontent.com/23466852/141679174-e7f674ac-284f-4295-b878-2d2061254b07.png)

**Comment by masagrator** [comment]
> i just download the lasted source code from github

It seems you didn't. In master those lines are completely different than what errors show.

**Comment by masagrator** [comment]
Don't download source code from releases, as they are outdated.

https://github.com/WerWolv/libtesla/archive/refs/heads/master.zip

**Comment by sir1st** [comment]
before, i download the tag 1.3.3 code. now the master code is available, ty!
