### ISSUE TITLE
How to call accountGetPreselectedUser with the right way?

### ISSUE THREAD

**Issue by iamcco** [WerWolv/libtesla#69]
```c
        rc = accountInitialize(AccountServiceType_Administrator);
        if (R_SUCCEEDED(rc))
        {
            rc = accountGetPreselectedUser(&uid);
            if (R_FAILED(rc))
                PselUserSelectionSettings settings;
                memset(&settings, 0, sizeof(settings));

                rc = pselShowUserSelector(&uid, &settings);
            }
            accountExit();
        }
```

`accountGetPreselectedUser` and `pselShowUserSelector` all failed.

**Comment by iamcco** [comment]
call within `tsl::hlp::doWithSmSession` still doesn't help.

**Comment by masagrator** [comment]
You should provide error codes as they may be helpful.

**Comment by iamcco** [comment]
> You should provide error codes as they may be helpful.

@masagrator error code return from `accountGetPreselectedUser` is `0x1159` and from `pselShowUserSelector` is `0xe401`

**Comment by masagrator** [comment]
0x1159 means that account service is not initialized.

I see in libnx source that is possible to get success return from accountInitialize, but in fact it can fail. This would require debugging what exactly fails.

**Comment by HookedBehemoth** [comment]
That won't work as the "preselected user" is the user that launched your process. https://github.com/switchbrew/libnx/blob/master/nx/source/services/acc.c#L200
This is determined by asking applet. Tesla overlays aren't applets and not launched by a specific user. I think you are trying to do something else but I don't know if you are able to do it in this context.

**Comment by iamcco** [comment]
> That won't work as the "preselected user" is the user that launched your process. https://github.com/switchbrew/libnx/blob/master/nx/source/services/acc.c#L200 This is determined by asking applet. Tesla overlays aren't applets and not launched by a specific user. I think you are trying to do something else but I don't know if you are able to do it in this context.

Thanks for pointing that out, make more sense now.
